// Generated by LiveScript 1.4.0
(function(){
  var edge, hello;
  edge = require('edge');
  hello = edge.func('async (input) => { return ".NET welcomes " + input.ToString(); }');
  hello('Node.js', function(error, result){
    if (error) {
      throw error;
    }
    return console.log(result);
  });
}).call(this);
